import { Cinzel, Josefin_Sans } from "next/font/google";
import "react-image-gallery/styles/image-gallery.css";
import "./globals.css";
import Navigation from "@/components/Navigation/Navigation";
import { getAppGlobalServer } from "@/lib/init/appGlobalsInit.server";
import AppGlobalsInit from "@/lib/init/appGlobalsInit.client";
import Footer from "@/components/Sections/Footer/Footer";

const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

const josefinSans = Josefin_Sans({
  variable: "--font-josefin",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { navigation, properties, homeData, parishData, siteSettings } =
    await getAppGlobalServer();

  return (
    <html lang="en">
      <body
        className={`${cinzel.variable} ${josefinSans.variable} antialiased`}
      >
        <AppGlobalsInit
          globals={{
            navigation,
            properties,
            homeData,
            parishData,
            siteSettings,
          }}
        />
        <Navigation navigation={navigation} siteSettings={siteSettings} />
        {children}
        <Footer siteSettings={siteSettings} />
      </body>
    </html>
  );
}
