import { Cinzel, Josefin_Sans } from "next/font/google";
import "./globals.css";
import Footer from "./components/sections/Footer/Footer";

const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

const josefinSans = Josefin_Sans({
  variable: "--font-josefin",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${cinzel.variable} ${josefinSans.variable} antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
